title: Freeopcua.github.io
description: "FreeOpcUa: Open Source C++ and Python OPC-UA Server and Client Libraries and Tools"
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
